site_name: Alphabet Eurps
site_description: Everything you wanted to know and more about the elusive Alphabet Eurps.
site_author: Nicolas and Emily Ventura
copyright: eurps.nicfv.com &copy; 2024
repo_url: https://github.com/vfcin/eurps
theme: material
extra:
  generator: false
